### ISSUE TITLE
Failed to create process when building js files

### ISSUE THREAD

**Issue by emmauss** [Pewpews/happypandax#20]
the command `python build_js.py` returns `failed to create process.` in cmd on windows, while all previous build steps work. i am using python 3.5.2.

**Comment by Pewpews** [comment]
Hi, weird issue, first time I'm encountering this.
A quick google search leads me to believe it's an issue stemming from your python installation and not the js building step. But just to make sure:
- make sure you're in the virtual env
- run `python build_js.py` from the root HPX folder

My google research found these possible causes and solutions:
- Issue with Python path that contain spaces (this is likely it)
- Python 64bit being the culprit (i'm using 32bit)
- [this SO](https://stackoverflow.com/questions/17373265/pip-easy-install-failure-failed-to-create-process)

**Comment by Pewpews** [comment]
If the issue still persists, try doing this:
1. while in the virtual env
2. go into the `happypanda/webclient/static` folder
3. run this command `transcrypt -b -m -e 6 -n .\pages.py`

This is basically what the `build_js.py` script does.

**Comment by emmauss** [comment]
still `failed to create process` error.

**Comment by Pewpews** [comment]
Okay, that's interesting. Glad it worked.
